### ISSUE TITLE
No protocol handler if OneDrive is not yet installed

### ISSUE THREAD

**Issue by mardahl** [mardahl/PSBucket#2]
If the OneDrive Templates script is deployed to the user before OneDrive is setup, then the launch of the ODOPEN:// protocol, will result in windows asking what program to open it with.

A method to detect if OneDrive is running in the current users context, should be implemented.

**Comment by baardhermansen** [comment]
You could try with 
`Test-Path -Path $env:LOCALAPPDATA\Microsoft\OneDrive\settings\Business* -PathType Container`

The folder should not exist if OneDrive isn't installed.

**Comment by mardahl** [comment]
Sounds like a valid approach.
Will try and find time next week to test and add to the script :)

**Comment by baardhermansen** [comment]
I see Microsoft are using different method of checking. From https://docs.microsoft.com/en-us/onedrive/deploy-on-windows, Microsoft is only checking for the existence of OneDrive.exe in $env:LOCALAPPDATA\Microsoft\OneDrive\.
Reading the comments, some suggestions for improvement have been made, among them this one seems to be important: Line 25 - if ((Get-Item $OneDrive).VersionInfo.FileVersion -gt '18').

**Comment by mardahl** [comment]
Thanks Baard :)

**Comment by mardahl** [comment]
Because I have no time to test, I had to use an old trick form my OneDriveAutoMapper script, which will just look for the process for some time, and then exit if it never spawns. This works well.
