### ISSUE TITLE
Had to move some lines around

### ISSUE THREAD

**Issue by enroll-bacon** [mardahl/PSBucket#6]
The parts that set the values in the registry were not set, seems like the script was terminated before it got to that part.
Resolved that by moving that part up to just below where it calls the WaitForOneDrive function.
Also had to add a New-Item line to add the Options key if it was missing.

Also now the odopen url's I exported contained 'userID=' as well. Removed that as well from the variable.

**Comment by mardahl** [comment]
Hi Bacon! 👍 

I am guessing you are talking about the Office Templates script.

I am sure it could use some more code for robustness.

As it works for a lot of companies as is, I am not sure doing the changes you suggest, is a wise choice.
But if it works great for you, that's awesome 👍 , and I will leave this issue for others to read.

I do suggest however that you try and debug why the registry entries don't get set, as I have not heard this before.
In any case, you are welcome to do a pull request to the file, with your alterations, and I will have a look at them :)
